---
title: "Exploration"
author: "Armando Falcucci"
date: "2025-02-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(flextable)
```

```{r}

Cala <- read.csv("../data/Ca_3D_Dataset.csv") %>%
  mutate(Site = "Cala") %>%
  rename(Layer = Spit)

Castelcivita <- read.csv("../data/CTC_3D_Dataset.csv") %>%
  mutate(Site = "Castelcivita")

Bombrini <- read.csv("../data/RB_3D_Dataset.csv") %>%
  mutate(Site = "Bombrini")

Fumane <- read.csv("../data/RF_3D_Dataset.csv") %>%
  rename(Layer = Unit)

dataset <- rbind(Bombrini, Cala, Castelcivita, Fumane) %>%
  mutate(Scanner = recode(Scanner, "Artec.spider" = "Artec.Spider"))

```

## Exploration

```{r, echo=FALSE}
# Check the first few rows of the combined dataset
head(dataset)

# Summarize the dataset
summary(dataset)

# Check for missing values
colSums(is.na(dataset))

```


## Exploratory Data Analysis

```{r}
# Count the number of models per site
site_counts <- dataset %>%
  group_by(Site) %>%
  summarise(Number_of_Models = n())

# Plot the number of models per site
ggplot(site_counts, aes(x = Site, y = Number_of_Models, fill = Site)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Number of 3D Models per Site", x = "Site", y = "Number of Models")

```


```{r, echo=FALSE, warning=FALSE}
dataset %>%
tabyl(Site, Scanner) %>%
  adorn_totals("col") %>%
  adorn_totals("row") %>%
  adorn_percentages("row") %>%
  adorn_pct_formatting(digits = 1) %>%
  adorn_ns(position = "front") %>%
  flextable() %>%
  theme_vanilla() %>%
  set_table_properties(layout = "autofit") %>%
  autofit()
```


```{r}
# Count scanner usage per site
scanner_counts <- dataset %>%
  group_by(Site, Scanner) %>%
  summarise(Number_of_Models = n())

# Plot the scanner usage by site
ggplot(scanner_counts, aes(x = Site, y = Number_of_Models, fill = Scanner)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal() +
  labs(title = "Scanner Usage by Site", x = "Site", y = "Number of Models")

```

## Polygons and quality of the scans

to do

## Class

```{r}
# Count the number of models by Class and Site
class_counts <- dataset %>%
  group_by(Site, Class) %>%
  summarise(Number_of_Models = n())

# Plot the Class distribution by site
ggplot(class_counts, aes(x = Class, y = Number_of_Models, fill = Site)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal() +
  labs(title = "Class Distribution by Site", x = "Class", y = "Number of Models")

```

```{r}
# Assuming you have combined data and the necessary libraries loaded

dataset %>%
  mutate(Class = recode(Class, "Pebble" = "Hammerstone")) %>%
  ggstatsplot::ggbarstats(
    x = Class,  
    y = Site,
    palette = "Set2",
    results.subtitle = F) +
  theme_minimal() +
  # labs(subtitle = "a") +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    strip.text = element_text(size = 14),
    legend.position = "bottom",
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12),
    plot.subtitle = element_text(hjust = 0, vjust = -0.5, size = 16, face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1)  # Rotate y-axis labels by 45 degrees
  ) +
  guides(fill = guide_legend(title = "Site"))

```


```{r}
# Assuming you have combined data and the necessary libraries loaded

dataset %>%
  filter(!Blank %in% c("Other")) %>%
  filter(!Class %in% c("Core-Tool", "Core")) %>%
  mutate(Class = recode(Class, "Pebble" = "Hammerstone")) %>%
  ggstatsplot::ggbarstats(
    x = Blank,  
    y = Site,
    palette = "Set2",
    results.subtitle = F) +
  theme_minimal() +
  # labs(subtitle = "a") +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    strip.text = element_text(size = 14),
    legend.position = "bottom",
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12),
    plot.subtitle = element_text(hjust = 0, vjust = -0.5, size = 16, face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1)  # Rotate y-axis labels by 45 degrees
  ) +
  guides(fill = guide_legend(title = "Site"))

```


```{r}
# Assuming you have the dataset loaded as 'combined_data' and the necessary libraries loaded

# Plot using ggboxplot from ggstatsplot to visualize Volume by Scanner type
dataset %>%
  # Plotting Volume as the numeric variable and Scanner as the categorical grouping variable
  ggstatsplot::ggbetweenstats(
    x = Scanner,  # Categorical variable for the x-axis (Scanner type)
    y = Volume,   # Numeric variable for the y-axis (Volume)
    palette = "Set2",  # Color palette for boxplots
    results.subtitle = FALSE  # Disable subtitle for statistical results
  ) +
  # Customize the plot appearance
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),  # Title styling
    axis.title = element_text(size = 14),  # Axis titles styling
    axis.text = element_text(size = 12),  # Axis text styling
    strip.text = element_text(size = 14),  # Facet label styling
    legend.position = "bottom",  # Place legend at the bottom
    legend.title = element_text(size = 14),  # Legend title styling
    legend.text = element_text(size = 12),  # Legend text styling
    plot.subtitle = element_text(hjust = 0, vjust = -0.5, size = 16, face = "bold"),  # Subtitle customization
    axis.text.x = element_text(angle = 45, hjust = 1)  # Rotate x-axis labels by 45 degrees
  ) +
  # Customize the legend title if necessary
  guides(fill = guide_legend(title = "Scanner"))

```


```{r}
# Load the ggplot2 package
library(ggplot2)

# Plot the boxplot using ggplot2
ggplot(dataset, aes(x = Scanner, y = log10(Volume), fill = Scanner)) +
  geom_boxplot() +  # Create the boxplot
  theme_minimal() +  # Use a minimal theme
  labs(
    title = "",
    x = "Scanner Type",  # Label for the x-axis
    y = "Volume"         # Label for the y-axis
  ) +
  theme(
    plot.title = element_text(size = 16, face = "bold"),  # Title styling
    axis.title = element_text(size = 14),  # Axis titles styling
    axis.text = element_text(size = 12),  # Axis text styling
    axis.text.x = element_text(angle = 45, hjust = 1),  # Rotate x-axis labels for readability
    legend.position = "none"  # Remove the legend
  )

```


```{r}
# Plot the boxplot using ggplot2
ggplot(dataset, aes(x = Scanner, y = Length, fill = Scanner)) +
  geom_boxplot() +  # Create the boxplot
  theme_minimal() +  # Use a minimal theme
  labs(
    title = "Distribution of Volume by Scanner Type",
    x = "Scanner Type",  # Label for the x-axis
    y = "Length"         # Label for the y-axis
  ) +
  theme(
    plot.title = element_text(size = 16, face = "bold"),  # Title styling
    axis.title = element_text(size = 14),  # Axis titles styling
    axis.text = element_text(size = 12),  # Axis text styling
    axis.text.x = element_text(angle = 45, hjust = 1),  # Rotate x-axis labels for readability
    legend.position = "none"  # Remove the legend
  )
```

```{r}
# Count Preservation by site
preservation_counts <- dataset %>%
  group_by(Site, Preservation) %>%
  summarise(Number_of_Models = n())

# Plot Preservation counts by site
ggplot(preservation_counts, aes(x = Site, y = Number_of_Models, fill = Preservation)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal() +
  labs(title = "Preservation by Site", x = "Site", y = "Number of Models") # check the NAs from CTC
```


