---
title: "The Open Aurignacian Project: 3D scanning and the digital preservation of the Italian Paleolithic record"
author: "Armando Falcucci, Adriana Moroni, Fabio Negrino, Marco Peresani & Julien Riel-Salvatore"
date: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, warning=FALSE}
# Packages used
library(tidyverse)
library(flextable)
library(janitor)
library(ggplot2)
library(gridExtra)
library(cowplot)
```

```{r, echo=FALSE, warning=FALSE}
# Datasets loading
Cala <- read.csv("../data/Cala_3D_metadata.csv")

Castelcivita <- read.csv("../data/Castelcivita_3D_metadata.csv")

Bombrini <- read.csv("../data/Bombrini_3D_metadata.csv")

Fumane <- read.csv("../data/Fumane_3D_metadata.csv")

dataset <- rbind(Bombrini, Cala, Castelcivita, Fumane)

# write.csv(dataset, "../data/3D_Datasets.csv", row.names = FALSE)
```

## Tables

### Table 2

```{r, echo=FALSE, warning=FALSE}
dataset %>%
  mutate(Site = fct_relevel(Site, "Cala", "Castelcivita", "Fumane", "Bombrini")) %>%
tabyl(Site, Scanner) %>%
  adorn_totals("col") %>%
  adorn_totals("row") %>%
  adorn_percentages("row") %>%
  adorn_pct_formatting(digits = 1) %>%
  adorn_ns(position = "front") %>%
  flextable() %>%
  theme_vanilla() %>%
  set_table_properties(layout = "autofit") %>%
  autofit()
```


### Table 3

```{r, echo=FALSE, warning=FALSE}
dataset %>%
  mutate(Site = fct_relevel(Site, "Cala", "Castelcivita", "Fumane", "Bombrini")) %>%
  mutate(Preservation = recode(Preservation, "Other" = "Other/Undet", "Undetermined" = "Other/Undet")) %>%
  mutate(Preservation = fct_relevel(Preservation, "Complete", "Proximal", "Mesial", "Distal", "Other/Undet")) %>%
  filter(Class == "Blank") %>%
tabyl(Site, Preservation) %>%
  adorn_totals("col") %>%
  adorn_totals("row") %>%
  adorn_percentages("row") %>%
  adorn_pct_formatting(digits = 1) %>%
  adorn_ns(position = "front") %>%
  flextable() %>%
  theme_vanilla() %>%
  set_table_properties(layout = "autofit") %>%
  autofit()
```

### Table 4

```{r, echo=FALSE, warning=FALSE}
dataset %>%
  mutate(Site = fct_relevel(Site, "Cala", "Castelcivita", "Fumane", "Bombrini")) %>%
  mutate(Preservation = recode(Preservation, "Other" = "Other/Undet", "Undetermined" = "Other/Undet")) %>%
  mutate(Preservation = fct_relevel(Preservation, "Complete", "Proximal", "Mesial", "Distal", "Other/Undet")) %>%
  filter(Class == "Tool") %>%
tabyl(Site, Preservation) %>%
  adorn_totals("col") %>%
  adorn_totals("row") %>%
  adorn_percentages("row") %>%
  adorn_pct_formatting(digits = 1) %>%
  adorn_ns(position = "front") %>%
  flextable() %>%
  theme_vanilla() %>%
  set_table_properties(layout = "autofit") %>%
  autofit()
```


## Figures

### Figure 3a
```{r}
Figure_3a <- dataset %>%
  mutate(Scanner = recode(Scanner, "Artec.Spider-1" = "Artec Spider", "Artec.Micro-1" = "Artec Micro", "Micro-CT (Phoenix v-tome-x s, General Electronics)" = "Micro-CT")) %>%
  ggplot(aes(x = Scanner, y = log(Volume), fill = Scanner)) +
  geom_boxplot(alpha = 0.8) +
  geom_jitter(width = 0.25, size = 2, color = "black", alpha = 0.15) +
  theme_minimal() +
  labs(
    title = "",
    x = "Scanner",
    y = "LogVolume"
  ) +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  )

Figure_3a
# ggsave("../output/plot_volume.tiff", plot_volume, width = 6, height = 4, dpi = 300)
```


### Figure 3b
```{r}
Figure_3b <- dataset %>%
  mutate(Scanner = recode(Scanner, "Artec.Spider-1" = "Artec Spider", "Artec.Micro-1" = "Artec Micro", "Micro-CT (Phoenix v-tome-x s, General Electronics)" = "Micro-CT")) %>%
  ggplot(aes(x = Avg_edge_length.mm..Resolution, fill = Scanner)) +
  geom_density(alpha = 0.8) +
  theme_minimal() +
  labs(
    title = "",
    x = "Resolution (average edge length)",
    y = "Density",
    fill = "Scanner"
  ) +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    legend.position = "bottom"
  )

Figure_3b
```


### Figure 3
```{r}
Figure_3 <- plot_grid(Figure_3a, Figure_3b, ncol = 2, labels = c("a", "b")) +
  theme(plot.title = element_text(size = 16, face = "bold"))

Figure_3

ggsave("../output/Figure_3.pdf", Figure_3, width = 8, height = 4, dpi = 300)

ggsave("../output/Figure_3.tiff", Figure_3, width = 9, height = 4, dpi = 300)

```


### Figure 4
```{r}
Figure_4 <- dataset %>%
  mutate(Class = fct_relevel(Class, "Blank", "Core", "Core-Tool", "Tool", "Hammerstone")) %>%
  mutate(Class = recode(Class, "Pebble" = "Hammerstone")) %>%
  ggstatsplot::ggbarstats(
    x = Class,  
    y = Site,
    palette = "Set3",
    results.subtitle = F) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    strip.text = element_text(size = 14),
    legend.position = "bottom",
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12),
    plot.subtitle = element_text(hjust = 0, vjust = -0.5, size = 16, face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  guides(fill = guide_legend(title = "Class"))


ggsave("../output/Figure_4.pdf", Figure_4, width = 8, height = 6, dpi = 300)

ggsave("../output/Figure_4.tiff", Figure_4, width = 8, height = 6, dpi = 300)

```


### Figure 6

```{r}
Fig6a <- dataset %>%
  filter(!Blank %in% c("Other")) %>%
  filter(!Class %in% c("Core-Tool", "Core", "Tool")) %>%
  ggstatsplot::ggbarstats(
    x = Blank,  
    y = Site,
    palette = "Set2",
    results.subtitle = F) +
  theme_minimal() +
  labs(title = "a") +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    strip.text = element_text(size = 14),
    legend.position = "bottom",
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12),
    plot.subtitle = element_text(hjust = 0, vjust = -0.5, size = 16, face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  guides(fill = guide_legend(title = "Blank type"))


Fig6b <- dataset %>%
  filter(!Blank %in% c("Other", "Undetermined")) %>%
  filter(!Class %in% c("Core-Tool", "Core", "Blank")) %>%
  ggstatsplot::ggbarstats(
    x = Blank,  
    y = Site,
    palette = "Set2",
    results.subtitle = F) +
  theme_minimal() +
  labs(title = "b") +
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    strip.text = element_text(size = 14),
    legend.position = "bottom",
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12),
    plot.subtitle = element_text(hjust = 0, vjust = -0.5, size = 16, face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  guides(fill = guide_legend(title = "Blank type"))

Figure_6 <- (Fig6a | Fig6b) + 
  patchwork::plot_layout(guides = "collect") & 
  theme(legend.position = "bottom")

ggsave("../output/Figure_6.pdf", Figure_6, width = 8, height = 5, dpi = 300)

ggsave("../output/Figure_6.tiff", Figure_6, width = 8, height = 5, dpi = 300)
```
